# Generated by Django 4.1.5 on 2023-01-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasksdata_about_alter_tasksdata_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdata',
            name='update_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
