# Generated by Django 4.1.5 on 2023-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasksdata_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdata',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='tasksdata',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksdata',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
