# Generated by Django 4.1.5 on 2023-01-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_tasksdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdata',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
