# Generated by Django 4.1.5 on 2023-02-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tasksdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdata',
            name='update_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
