# Generated by Django 4.1.5 on 2023-02-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_tasksdata_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdata',
            name='date_completed',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
